language: r
sudo: false
cache: packages

r:
 - 3.2
 - 3.3
 - 3.4
 - oldrel
 - release
 - devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov(line_exclusions = list("src/miniz.h", "src/miniz.c"))'

env:
  global:
    - NOT_CRAN=true
    - ZIP_LONG_TESTS=true
