language: r
sudo: false
cache: packages

r:
 - release
 - devel
 - oldrel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov(line_exclusions = list("src/miniz.h", "src/zip.h", "src/zip.c"))'
